import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import StoreProvider from "@/lib/store/StoreProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={cn("antialiased font-Roboto")}>
                <StoreProvider>
                    <Toaster expand={true} closeButton />
                    {children}
                </StoreProvider>
            </body>
        </html>
    );
}
